"""
Revenue Attribution & Analytics Engine
Tracks revenue generated by advertising campaigns and calculates ROI
"""

import os
import json
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone, timedelta
import logging
from enum import Enum

logger = logging.getLogger(__name__)


class AttributionModel(Enum):
    """Attribution models for credit allocation"""
    FIRST_TOUCH = "first_touch"
    LAST_TOUCH = "last_touch"
    LINEAR = "linear"
    TIME_DECAY = "time_decay"
    POSITION_BASED = "position_based"


class RevenueAttributionEngine:
    """Track revenue from campaigns and attribute sales to ad sources"""
    
    def __init__(self):
        self.db = None
    
    async def set_db(self, database):
        """Set database connection"""
        self.db = database
    
    async def record_sale(self,
                         product_id: str,
                         amount: float,
                         source: str = "organic",
                         campaign_id: Optional[str] = None,
                         platform: Optional[str] = None,
                         user_id: Optional[str] = None) -> Dict[str, Any]:
        """
        Record a sale and attribute it to campaign(s)
        
        Args:
            product_id: Product sold
            amount: Sale amount
            source: Sale source (organic, direct, campaign, etc)
            campaign_id: Campaign ID if from ads
            platform: Platform name if from ads
            user_id: Buyer user ID
            
        Returns:
            Sale record with attribution
        """
        
        try:
            if not self.db:
                return {"error": "Database not configured"}
            
            sale_record = {
                "sale_id": str(uuid.uuid4()),
                "product_id": product_id,
                "amount": amount,
                "source": source,
                "campaign_id": campaign_id,
                "platform": platform,
                "user_id": user_id,
                "attributed_campaign_credit": {},
                "created_at": datetime.now(timezone.utc).isoformat()
            }
            
            # Attribute revenue to campaign(s)
            if campaign_id:
                # Get campaign
                campaign = await self.db.campaigns.find_one(
                    {"campaign_id": campaign_id},
                    {"_id": 0}
                )
                
                if campaign:
                    # Distribute credit among platforms in campaign
                    num_platforms = len(campaign.get("platform_campaigns", {}))
                    if num_platforms > 0:
                        credit_per_platform = amount / num_platforms
                        
                        for plat in campaign.get("platform_campaigns", {}).keys():
                            sale_record["attributed_campaign_credit"][plat] = credit_per_platform
            
            # Save sale
            await self.db.sales.insert_one(sale_record)
            
            # Update campaign metrics if applicable
            if campaign_id:
                await self.db.campaigns.update_one(
                    {"campaign_id": campaign_id},
                    {
                        "$inc": {
                            "total_revenue": amount,
                            "total_conversions": 1
                        }
                    }
                )
            
            return {
                "sale_id": sale_record["sale_id"],
                "status": "recorded",
                "amount": amount,
                "attributed_to": sale_record["attributed_campaign_credit"]
            }
        
        except Exception as e:
            logger.error(f"Failed to record sale: {str(e)}")
            return {"error": str(e)}
    
    async def get_campaign_roi(self,
                              campaign_id: str,
                              attribution_model: str = "last_touch") -> Dict[str, Any]:
        """
        Calculate ROI for a campaign
        
        Args:
            campaign_id: Campaign ID
            attribution_model: Attribution model to use
            
        Returns:
            ROI metrics
        """
        
        try:
            if not self.db:
                return {"error": "Database not configured"}
            
            campaign = await self.db.campaigns.find_one(
                {"campaign_id": campaign_id},
                {"_id": 0}
            )
            
            if not campaign:
                return {"error": "Campaign not found"}
            
            # Get spend data
            total_spend = 0.0
            for platform_data in campaign.get("platform_campaigns", {}).values():
                total_spend += platform_data.get("spend", 0)
            
            # Get revenue data based on attribution model
            revenue = await self._get_attributed_revenue(
                campaign_id=campaign_id,
                model=attribution_model
            )
            
            profit = revenue - total_spend
            roi = (profit / max(total_spend, 1)) * 100
            
            return {
                "campaign_id": campaign_id,
                "product_id": campaign.get("product_id"),
                "attribution_model": attribution_model,
                "total_spend": total_spend,
                "attributed_revenue": revenue,
                "profit": profit,
                "roi_percent": roi,
                "roi_status": "excellent" if roi > 200 else "good" if roi > 100 else "poor" if roi < 0 else "moderate",
                "payback_period_days": self._calculate_payback_period(total_spend, revenue, campaign.get("duration_days", 30))
            }
        
        except Exception as e:
            logger.error(f"Failed to calculate ROI: {str(e)}")
            return {"error": str(e)}
    
    async def get_platform_attribution(self, campaign_id: str) -> Dict[str, Any]:
        """
        Get revenue attribution breakdown by platform
        """
        
        try:
            if not self.db:
                return {"error": "Database not configured"}
            
            campaign = await self.db.campaigns.find_one(
                {"campaign_id": campaign_id},
                {"_id": 0}
            )
            
            if not campaign:
                return {"error": "Campaign not found"}
            
            # Get sales attributed to this campaign
            sales = await self.db.sales.find(
                {"campaign_id": campaign_id},
                {"_id": 0}
            ).to_list(None)
            
            # Aggregate by platform
            platform_revenue = {}
            platform_spend = {}
            
            for platform, platform_data in campaign.get("platform_campaigns", {}).items():
                platform_spend[platform] = platform_data.get("spend", 0)
                platform_revenue[platform] = 0.0
            
            # Sum attributed revenue
            for sale in sales:
                for platform, credit in sale.get("attributed_campaign_credit", {}).items():
                    platform_revenue[platform] = platform_revenue.get(platform, 0) + credit
            
            # Calculate ROI per platform
            platform_roi = {}
            for platform in platform_spend.keys():
                spend = platform_spend.get(platform, 0)
                revenue = platform_revenue.get(platform, 0)
                profit = revenue - spend
                roi = (profit / max(spend, 1)) * 100 if spend > 0 else 0
                
                platform_roi[platform] = {
                    "spend": spend,
                    "revenue": revenue,
                    "profit": profit,
                    "roi_percent": roi,
                    "efficiency": "excellent" if roi > 200 else "good" if roi > 100 else "poor"
                }
            
            # Sort by ROI
            sorted_platforms = sorted(
                platform_roi.items(),
                key=lambda x: x[1]["roi_percent"],
                reverse=True
            )
            
            return {
                "campaign_id": campaign_id,
                "by_platform": dict(sorted_platforms),
                "best_performer": sorted_platforms[0][0] if sorted_platforms else None,
                "top_3": dict(sorted_platforms[:3])
            }
        
        except Exception as e:
            logger.error(f"Failed to get platform attribution: {str(e)}")
            return {"error": str(e)}
    
    async def get_time_series_roi(self,
                                  campaign_id: str,
                                  interval: str = "daily") -> List[Dict[str, Any]]:
        """
        Get ROI over time for a campaign
        
        Args:
            campaign_id: Campaign ID
            interval: "hourly", "daily", "weekly"
            
        Returns:
            Time series of ROI metrics
        """
        
        try:
            if not self.db:
                return []
            
            campaign = await self.db.campaigns.find_one(
                {"campaign_id": campaign_id},
                {"_id": 0}
            )
            
            if not campaign:
                return []
            
            start_date = datetime.fromisoformat(campaign.get("created_at", ""))
            end_date = start_date + timedelta(days=campaign.get("duration_days", 30))
            
            # Get sales
            sales = await self.db.sales.find(
                {
                    "campaign_id": campaign_id,
                    "created_at": {
                        "$gte": start_date.isoformat(),
                        "$lte": end_date.isoformat()
                    }
                },
                {"_id": 0}
            ).to_list(None)
            
            # Group by time interval
            time_buckets = {}
            
            for sale in sales:
                sale_date = datetime.fromisoformat(sale.get("created_at", ""))
                
                if interval == "hourly":
                    bucket_key = sale_date.replace(minute=0, second=0, microsecond=0).isoformat()
                elif interval == "weekly":
                    week_start = sale_date - timedelta(days=sale_date.weekday())
                    bucket_key = week_start.date().isoformat()
                else:  # daily
                    bucket_key = sale_date.date().isoformat()
                
                if bucket_key not in time_buckets:
                    time_buckets[bucket_key] = {
                        "timestamp": bucket_key,
                        "revenue": 0,
                        "conversions": 0,
                        "roi_percent": 0
                    }
                
                time_buckets[bucket_key]["revenue"] += sale.get("amount", 0)
                time_buckets[bucket_key]["conversions"] += 1
            
            # Calculate cumulative metrics
            result = []
            cumulative_revenue = 0
            cumulative_spend = 0
            
            for bucket_key in sorted(time_buckets.keys()):
                cumulative_revenue += time_buckets[bucket_key]["revenue"]
                cumulative_spend += self._get_spend_for_period(campaign, bucket_key)
                
                roi = ((cumulative_revenue - cumulative_spend) / max(cumulative_spend, 1)) * 100
                
                result.append({
                    "timestamp": bucket_key,
                    "cumulative_revenue": cumulative_revenue,
                    "cumulative_spend": cumulative_spend,
                    "cumulative_roi_percent": roi,
                    "period_revenue": time_buckets[bucket_key]["revenue"],
                    "period_conversions": time_buckets[bucket_key]["conversions"]
                })
            
            return result
        
        except Exception as e:
            logger.error(f"Failed to get time series ROI: {str(e)}")
            return []
    
    async def get_revenue_dashboard(self, product_id: Optional[str] = None) -> Dict[str, Any]:
        """
        Get comprehensive revenue and attribution dashboard
        """
        
        try:
            if not self.db:
                return {"error": "Database not configured"}
            
            # Get all campaigns
            query = {}
            if product_id:
                query["product_id"] = product_id
            
            campaigns = await self.db.campaigns.find(query, {"_id": 0}).to_list(None)
            
            total_revenue = 0
            total_spend = 0
            total_roi = 0
            total_conversions = 0
            campaigns_by_status = {}
            platform_summary = {}
            
            for campaign in campaigns:
                roi_data = await self.get_campaign_roi(campaign["campaign_id"])
                
                if "error" not in roi_data:
                    total_revenue += roi_data.get("attributed_revenue", 0)
                    total_spend += roi_data.get("total_spend", 0)
                    total_conversions += campaign.get("total_conversions", 0)
                
                # Track by status
                status = campaign.get("status", "unknown")
                campaigns_by_status[status] = campaigns_by_status.get(status, 0) + 1
                
                # Platform summary
                for platform, data in campaign.get("platform_campaigns", {}).items():
                    if platform not in platform_summary:
                        platform_summary[platform] = {
                            "campaigns": 0,
                            "total_spend": 0,
                            "total_revenue": 0
                        }
                    platform_summary[platform]["campaigns"] += 1
                    platform_summary[platform]["total_spend"] += data.get("spend", 0)
            
            overall_roi = ((total_revenue - total_spend) / max(total_spend, 1)) * 100 if total_spend > 0 else 0
            
            return {
                "total_campaigns": len(campaigns),
                "campaigns_by_status": campaigns_by_status,
                "financial_summary": {
                    "total_spend": total_spend,
                    "total_revenue": total_revenue,
                    "total_profit": total_revenue - total_spend,
                    "overall_roi_percent": overall_roi,
                    "total_conversions": total_conversions,
                    "cost_per_conversion": total_spend / max(total_conversions, 1)
                },
                "platform_performance": platform_summary,
                "action_items": self._generate_action_items(overall_roi, total_conversions, total_spend)
            }
        
        except Exception as e:
            logger.error(f"Failed to get revenue dashboard: {str(e)}")
            return {"error": str(e)}
    
    async def _get_attributed_revenue(self,
                                     campaign_id: str,
                                     model: str = "last_touch") -> float:
        """Get revenue attributed to campaign using specified model"""
        
        sales = await self.db.sales.find(
            {"campaign_id": campaign_id},
            {"_id": 0}
        ).to_list(None)
        
        if not sales:
            return 0.0
        
        if model == "last_touch":
            return sum(s.get("amount", 0) for s in sales)
        
        elif model == "first_touch":
            # Would require tracking first touch in user journey
            return sum(s.get("amount", 0) for s in sales) * 0.5
        
        elif model == "linear":
            return sum(s.get("amount", 0) for s in sales) * 0.8
        
        else:  # default to last touch
            return sum(s.get("amount", 0) for s in sales)
    
    def _calculate_payback_period(self, spend: float, revenue: float, duration_days: int) -> float:
        """Calculate payback period in days"""
        
        if revenue <= 0:
            return float('inf')
        
        daily_profit = (revenue - spend) / max(duration_days, 1)
        
        if daily_profit <= 0:
            return float('inf')
        
        return spend / daily_profit
    
    def _get_spend_for_period(self, campaign: Dict[str, Any], period_key: str) -> float:
        """Estimate spend for a time period"""
        
        duration_days = campaign.get("duration_days", 30)
        total_spend = sum(
            p.get("spend", 0) 
            for p in campaign.get("platform_campaigns", {}).values()
        )
        
        return total_spend / max(duration_days, 1)
    
    def _generate_action_items(self,
                              roi: float,
                              conversions: int,
                              spend: float) -> List[str]:
        """Generate recommended actions based on performance"""
        
        actions = []
        
        if roi < 0:
            actions.append("CRITICAL: Campaigns are unprofitable. Pause and review targeting.")
        elif roi < 100:
            actions.append("ROI is below target (100%+). Consider optimizing ad creative or targeting.")
        else:
            actions.append("ROI is healthy. Consider scaling successful campaigns.")
        
        if conversions == 0:
            actions.append("No conversions yet. Give campaigns more time or increase budget.")
        elif conversions < 5:
            actions.append("Low conversion volume. Collect more data before optimizing.")
        
        if spend > 5000:
            actions.append("High spend. Monitor daily. Consider A/B testing to improve efficiency.")
        
        return actions


import uuid
